---
- name: deploy to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy WAR file to tomcat
      copy:
        src: "/home/web3/MavenAnsibleWebApp1/target/MavenAnsibleWebApp1.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp1.war"
	    remote_src: no
    - name: Restart Tomcat
      systemd:
        name: tomcat
	state: restarted
	
