 ---
- hosts: web
  become: yes

  tasks:
    - name: copy WAR file to tomcat
      copy:
        src: /var/lib/jenkins/workspace/MavenAnsibleWebApp1/target/MavenAnsibleWebApp1.war
        dest: /opt/tomcat/webapps/MavenAnsibleWebApp1.war
        remote_src: no
